/LArSIMple/UseNeutrinoEvents true
/LArSIMple/NeutrinoInputFile /dune/data/users/lwhite86/gibuu/nc/gibuu_nc_1000_49.dat
/LArSIMple/NeutrinoFileType 2
/LArSIMple/UseRandomNeutrinoVertex false 
/LArSIMple/SetNeutrinoVertex 0.0 0.0 -200. cm 

/LArSIMple/OutputFileDir /dune/data/users/lwhite86/LArSIMple/gibuu/nc/49/
/LArSIMple/OutputFilePrefix LArSIMple_neutrino

/random/setSeeds 1234 5678

/run/beamOn 1000
