/LArSIMple/UseNeutrinoEvents true
/LArSIMple/NeutrinoInputFile /dune/data/users/lwhite86/genie/mcSample/nc/nc_1000_events_seed_50.dat
/LArSIMple/NeutrinoFileType 0
/LArSIMple/UseRandomNeutrinoVertex false 
/LArSIMple/SetNeutrinoVertex 0.0 0.0 -200. cm 

/LArSIMple/OutputFileDir /dune/data/users/lwhite86/LArSIMple/nc/0/
#/LArSIMple/OutputFileDir /dune/app/users/lwhite86/toyG4/LArSIMple/
/LArSIMple/OutputFilePrefix LArSIMple_neutrino

/random/setSeeds 1234 5678

/run/beamOn 1000
