/LArSIMple/UseNeutrinoEvents false
/LArSIMple/UseParticleBombs true

/LArSIMple/TruthFolding/FoldDeltaRays false

/LArSIMple/ParticleBomb/NMuon 1
/LArSIMple/ParticleBomb/NElectron 1
/LArSIMple/ParticleBomb/NProton 0
/LArSIMple/ParticleBomb/NNeutron 0
/LArSIMple/ParticleBomb/NPiZero 1
/LArSIMple/ParticleBomb/NPiPlus 0
/LArSIMple/ParticleBomb/NPiMinus 0
/LArSIMple/ParticleBomb/NKZero 0
/LArSIMple/ParticleBomb/NKPlus 0
/LArSIMple/ParticleBomb/NKMinus 0

/LArSIMple/ParticleBomb/MinimumKineticEnergy 100.
/LArSIMple/ParticleBomb/MaximumKineticEnergy 2500.

/LArSIMple/ParticleBomb/UseCone true
/LArSIMple/ParticleBomb/ConeAngle 45

/LArSIMple/OutputFileDir /usera/lwhitehead/LArSIMple/LArSIMple/
#/LArSIMple/OutputFileDir /exp/dune/app/users/lwhite86/toyG4/LArSIMple/
#/LArSIMple/OutputFileDir ~/LArSIMple/LArSIMple/
/LArSIMple/OutputFilePrefix LArSIMple_particle_bomb_1mu_1e_1pi0

/random/setSeeds 1234 5678

/run/beamOn 1

